site_name: Tự học đại học - Khu học mở
site_description: Một trang hướng dẫn tự học đại học ngay tại nhà cho rất nhiều ngành thông qua các nguồn tài nguyên miễn phí trên Internet
site_author: duykhanh471  
repo_name: Đóng góp & chỉnh sửa trang
repo_url: https://github.com/daihocmo/tu-hoc-dai-hoc

nav:
  - 'Trang chủ': index.md
  - 'Nghệ thuật':
    - 'Hội họa': 
      - 'Giới thiệu': 'nghe-thuat/hoi-hoa/index.md'
      - 'Bài nhập môn': 'nghe-thuat/hoi-hoa/nhap-mon.md'
      - 'Giáo trình': 'nghe-thuat/hoi-hoa/giao-trinh.md'
      - 'Tài nguyên': 'nghe-thuat/hoi-hoa/tai-nguyen.md'
    - 'Điêu khắc': 'nghe-thuat/dieu-khac.md'
    - 'Âm nhạc học': 'nghe-thuat/am-nhac.md'
    - 'Nhiếp ảnh': 'nghe-thuat/nhiep-anh.md'
    - 'Thiết kế đồ họa': 'nghe-thuat/thiet-ke-do-hoa/index.md'
  - 'Nhóm ngành Nhân văn':
      - 'Sáng tác văn học': 'nhan-van/sang-tac-van-hoc.md'
      - 'Triết học': 'nhan-van/triet-hoc.md'
      - 'Tôn giáo học': 
        - 'Nhập môn': 'nhan-van/ton-giao-hoc/index.md'
        - 'Giáo trình': 'nhan-van/ton-giao-hoc/giao-trinh.md'
      - 'Lịch sử':   
        - 'Giáo trình': 'nhan-van/lich-su/index.md'
        - 'Lịch sử Việt Nam':
          - 'Lộ trình lịch sử': 'nhan-van/lich-su/qua-trinh-lich-su-viet-nam.md'
        - 'Lịch sử thế giới':
          - 'Châu Á': 'nhan-van/lich-su/chau-a.md'
          - 'Châu Âu': 'nhan-van/lich-su/chau-au.md'
          - 'Châu Phi': 'nhan-van/lich-su/chau-phi.md'
          - 'Châu Mĩ': 'nhan-van/lich-su/chau-mi.md'
        - 'Lịch sử cổ đại':
          - 'Ai Cập cổ đại': 'nhan-van/lich-su/ai-cap-co-dai.md'
          - 'Hy Lạp cổ đại': 'nhan-van/lich-su/hy-lap-co-dai.md'
          - 'Persia cổ đại': 'nhan-van/lich-su/persia-co-dai.md'
          - 'Rome': 'nhan-van/lich-su/rome.md'
          - 'Thời trung cổ': 'nhan-van/lich-su/lich-su-trung-co.md'
        - 'Tài nguyên học': 'nhan-van/lich-su/tai-nguyen-hoc.md'
  - 'Khoa học xã hội và hành vi':
      - 'Xã hội học': 'khoa-hoc-xa-hoi/xa-hoi-hoc.md'
      - 'Nhân học': 'khoa-hoc-xa-hoi/nhan-hoc.md'
      - 'Tâm lý học': 'khoa-hoc-xa-hoi/tam-ly-hoc.md'
      - 'Tâm lý học lâm sàng': 'khoa-hoc-xa-hoi/tam-ly-hoc-lam-sang.md'
      - 'Quốc tế học': 'khoa-hoc-xa-hoi/quoc-te-hoc.md'
  - 'Báo chí và thông tin':
      - 'Báo chí': 'bao-chi-thong-tin/bao-chi.md'
      - 'Truyền thông đa phương tiện': 'bao-chi-thong-tin/truyen-thong-da-phuong-tien.md'
      - 'Xuất bản': 'bao-chi-thong-tin/xuat-ban.md'
  - 'Kinh doanh và quản lý':
      - 'Kinh tế học': 'kinh-doanh/kinh-te.md'
      - 'Marketing': 'kinh-doanh/marketing.md'
      - 'Thương mại điện tử': 'kinh-doanh/thuong-mai-dien-tu.md'
      - 'Tài chính – Ngân hàng': 'kinh-doanh/tai-chinh-ngan-hang.md'
      - 'Kế toán': 'kinh-doanh/ke-toan.md'
      - 'Quản lý dự án': 'kinh-doanh/quan-ly-du-an.md'
  - 'Khoa học sự sống':
      - 'Công nghệ Sinh học': 'khoa-hoc-su-song/cong-nghe-sinh-hoc.md'
  - 'Khoa học tự nhiên':
      - 'Vật lý học': 'khoa-hoc-tu-nhien/vat-ly-hoc.md'
      - 'Hóa học': 'khoa-hoc-tu-nhien/hoa-hoc.md'
      - 'Khoa học môi trường': 'khoa-hoc-tu-nhien/khoa-hoc-moi-truong.md'
  - 'Toán và thống kê':
      - 'Toán học': 'toan-va-thong-ke/toan-hoc.md'
      - 'Khoa học dữ liệu': 'toan-va-thong-ke/khoa-hoc-du-lieu.md'
      - 'Thống kê': 'toan-va-thong-ke/thong-ke.md'
  - 'Khoa học máy tính':
      - 'Khoa học máy tính': 'cong-nghe/khoa-hoc-may-tinh.md'
      - 'An toàn thông tin': 'cong-nghe/an-toan-thong-tin.md'
  - 'Sản xuất, chế biến':
      - 'Công nghệ thực phẩm': 'san-xuat-che-bien/cong-nghe-thuc-pham.md'
  - 'Kiến trúc và Xây dựng':
      - 'Kiến trúc': 'kien-truc-xay-dung/kien-truc.md'
      - 'Thiết kế nội thất': 'kien-truc-xay-dung/thiet-ke-noi-that.md'
  - 'Nông, lâm nghiệp, thủy sản':
      - 'Khoa học nông nghiệp': 'nong-lam-thuy-san/khoa-hoc-nong-nghiep.md'
      - 'Lâm học': 'nong-lam-thuy-san/lam-nghiep.md'
  - 'Nhóm ngành Sức khỏe':
      - 'Y khoa': 'y-khoa/y-khoa.md'
      - 'Dinh dưỡng': 'y-khoa/dinh-duong.md'
      - 'Y học cổ truyền': 'y-khoa/y-hoc-co-truyen.md'
  - 'Dịch vụ xã hội':
      - 'Công tác xã hội': 'dich-vu-xa-hoi/cong-tac-xa-hoi.md'
  - 'Cộng đồng & Tài nguyên học': cong-dong-tai-nguyen.md 

theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - toc.follow
    - search.highlighting
    - search.share
    - search.suggest
  name: material
  
plugins:
  - search
  - open-in-new-tab
      
      
extra:
  generator: false